# Generated by Django 3.0.7 on 2020-06-29 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cse',
            name='students',
        ),
        migrations.RemoveField(
            model_name='ece',
            name='students',
        ),
        migrations.RemoveField(
            model_name='eee',
            name='students',
        ),
        migrations.RemoveField(
            model_name='firstyear',
            name='students',
        ),
        migrations.RemoveField(
            model_name='fourthyear',
            name='students',
        ),
        migrations.RemoveField(
            model_name='mec',
            name='students',
        ),
        migrations.RemoveField(
            model_name='secondyear',
            name='students',
        ),
        migrations.RemoveField(
            model_name='thirdyear',
            name='students',
        ),
        migrations.DeleteModel(
            name='CIV',
        ),
        migrations.DeleteModel(
            name='CSE',
        ),
        migrations.DeleteModel(
            name='ECE',
        ),
        migrations.DeleteModel(
            name='EEE',
        ),
        migrations.DeleteModel(
            name='FirstYear',
        ),
        migrations.DeleteModel(
            name='FourthYear',
        ),
        migrations.DeleteModel(
            name='MEC',
        ),
        migrations.DeleteModel(
            name='SecondYear',
        ),
        migrations.DeleteModel(
            name='ThirdYear',
        ),
    ]
