# Generated by Django 3.0.7 on 2020-06-29 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200629_2125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='college',
            field=models.CharField(choices=[('Kiet', 'Kiet'), ('Kiek', 'Kiet+'), ('Kietw', 'KietW')], max_length=10),
        ),
    ]
