# Generated by Django 3.0.7 on 2020-06-29 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20200630_0025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='year',
            field=models.IntegerField(choices=[(0, '-----'), (1, 'I'), (2, 'II'), (3, 'III'), (4, 'IV')], default=0),
        ),
    ]
