# Generated by Django 3.0.7 on 2020-07-01 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_userprofile_is_leader'),
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='updates',
            name='access',
            field=models.ManyToManyField(to='users.UserGroup'),
        ),
    ]
