# Generated by Django 3.0.7 on 2020-07-01 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_auto_20200701_1747'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='headline',
            field=models.TextField(default=''),
        ),
    ]
