# Generated by Django 3.0.7 on 2020-06-29 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nask', '0004_auto_20200629_1350'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='task',
            name='year',
        ),
    ]
